# Site settings
title: Jaguaribetech
header-img: img/home-bg.jpg
email: lucachaves@gmail.com
copyright_name: Feito com Jekyll e ‚ù§
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/jaguaribetech"
url: "http://ifpb.github.io"
twitter_username: luizcarlosjp
github_username:  ifpb
# facebook_username:  StartBootstrap
email_username:  lucachaves@gmail.com
feed_xml: false

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-1523172-4

# Build settings
markdown: kramdown
highlighter: rouge
linenos: true
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
